// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

// MARK: - TaskState

/// Defines the possible lifecycle states of an ``A2ATask``.
///
/// Uses kebab-case raw values to match the Dart `@JsonEnum(fieldRename: FieldRename.kebab)`.
///
/// Mirrors Dart `TaskState` in `a2a/core/task.dart`.
public enum TaskState: String, Codable, Sendable, Equatable {
    case submitted
    case working
    case inputRequired = "input-required"
    case completed
    case canceled
    case failed
    case rejected
    case authRequired = "auth-required"
    case unknown
}

// MARK: - TaskStatus

/// Represents the status of an ``A2ATask`` at a specific point in time.
///
/// Mirrors Dart `TaskStatus` in `a2a/core/task.dart`.
public struct TaskStatus: Codable, Sendable, Equatable {

    /// The current state in the task's lifecycle.
    public let state: TaskState

    /// An optional, human-readable ``A2AMessage`` providing more details about
    /// the current status.
    public let message: A2AMessage?

    /// The timestamp when this status was recorded.
    public let timestamp: String?

    public init(
        state: TaskState,
        message: A2AMessage? = nil,
        timestamp: String? = nil
    ) {
        self.state = state
        self.message = message
        self.timestamp = timestamp
    }
}

// MARK: - A2ATask

/// Represents a stateful operation or conversation between a client and an agent.
///
/// An ``A2ATask`` encapsulates the entire lifecycle of an interaction, including
/// its current status, history of messages, and any generated artifacts.
///
/// Named `A2ATask` to avoid conflict with Swift Concurrency `Task`.
///
/// Mirrors Dart `Task` in `a2a/core/task.dart`.
public struct A2ATask: Codable, Sendable, Equatable {

    /// A unique identifier (e.g., UUID) for the task.
    public let id: String

    /// A server-generated unique identifier for grouping related tasks.
    public let contextId: String

    /// The current status of the task.
    public let status: TaskStatus

    /// An optional list of ``A2AMessage`` objects representing the conversation
    /// history of the task.
    public let history: [A2AMessage]?

    /// An optional collection of ``Artifact``s produced by the agent.
    public let artifacts: [Artifact]?

    /// Optional metadata for extensions.
    public let metadata: JSONObject?

    /// The timestamp of the last update to the task, in milliseconds since
    /// the Unix epoch.
    public let lastUpdated: Int?

    /// The type discriminator for this object, always "task".
    public let kind: String

    public init(
        id: String,
        contextId: String,
        status: TaskStatus,
        history: [A2AMessage]? = nil,
        artifacts: [Artifact]? = nil,
        metadata: JSONObject? = nil,
        lastUpdated: Int? = nil,
        kind: String = "task"
    ) {
        self.id = id
        self.contextId = contextId
        self.status = status
        self.history = history
        self.artifacts = artifacts
        self.metadata = metadata
        self.lastUpdated = lastUpdated
        self.kind = kind
    }
}

// MARK: - Artifact

/// Represents a file, data structure, or other resource generated by an agent
/// during an ``A2ATask``.
///
/// Mirrors Dart `Artifact` in `a2a/core/task.dart`.
public struct Artifact: Codable, Sendable, Equatable {

    /// A unique identifier for this artifact within the scope of the task.
    public let artifactId: String

    /// An optional, human-readable name for the artifact.
    public let name: String?

    /// An optional, human-readable description of the artifact's content or purpose.
    public let description: String?

    /// A list of ``Part`` objects that constitute the content of the artifact.
    public let parts: [Part]

    /// Optional metadata for extensions.
    public let metadata: JSONObject?

    /// Optional list of URIs for extensions that are relevant to this artifact.
    public let extensions: [String]?

    public init(
        artifactId: String,
        name: String? = nil,
        description: String? = nil,
        parts: [Part],
        metadata: JSONObject? = nil,
        extensions: [String]? = nil
    ) {
        self.artifactId = artifactId
        self.name = name
        self.description = description
        self.parts = parts
        self.metadata = metadata
        self.extensions = extensions
    }
}
